---
- name: Create Jakarta's GitLab VM 1
  hosts: jakarta_pc1
  remote_user: etudiant
  tasks:
  - include_role:
      name: vm_creation
      tasks_from: install
    vars:
      vm_ip: "{{ gitlab_1_ip }}"
      vm_name: gitlab1
      vm_memory: 4096

- name: Create Jakarta's GitLab VM 2
  hosts: jakarta_pc2
  remote_user: etudiant
  tasks:
  - include_role:
      name: vm_creation
      tasks_from: install
    vars:
      vm_ip: "{{ gitlab_2_ip }}"
      vm_name: gitlab2
      vm_memory: 4096

- name: Create Jakarta's GitLab VM 3
  hosts: jakarta_pc3
  remote_user: etudiant
  tasks:
  - include_role:
      name: vm_creation
      tasks_from: install
    vars:
      vm_ip: "{{ gitlab_3_ip }}"
      vm_name: gitlab3
      vm_memory: 4096

- name: Create Jakarta's GitLab VM 4
  hosts: jakarta_pc4
  remote_user: etudiant
  tasks:
  - include_role:
      name: vm_creation
      tasks_from: install
    vars:
      vm_ip: "{{ gitlab_4_ip }}"
      vm_name: gitlab4
      vm_memory: 4096

- name: Create Jakarta's GitLab VM 5 
  hosts: jakarta_pc5
  remote_user: etudiant
  tasks:
  - include_role:
      name: vm_creation
      tasks_from: install
    vars:
      vm_ip: "{{ gitlab_5_ip }}"
      vm_name: gitlab5
      vm_memory: 4096

- name: Install Java
  hosts: jakarta_gitlab
  remote_user: ansible
  become: true
  tasks:
  - import_role:
      name: java
      tasks_from: install

- name: Deploy Jakarta's GitLab service
  hosts: jakarta_gitlab
  remote_user: ansible
  become: true
  tasks:
  - import_role:
      name: gitlab
      tasks_from: install

- name: Update haproxy.cfg on load balancer machine
  hosts: jakarta_load_balancer
  remote_user: ansible
  become: true
  tasks:
  - lineinfile:
      dest: /etc/haproxy/haproxy.cfg
      insertafter: "^#gitlab_ips_here"
      line: "{{ item }}"
    with_items:
      - "\tserver node1 {{ gitlab_1_ip }}:{{ gitlab_port_in }} check"
      - "\tserver node2 {{ gitlab_2_ip }}:{{ gitlab_port_in }} check"
      - "\tserver node3 {{ gitlab_3_ip }}:{{ gitlab_port_in }} check"
      - "\tserver node4 {{ gitlab_4_ip }}:{{ gitlab_port_in }} check"
      - "\tserver node5 {{ gitlab_5_ip }}:{{ gitlab_port_in }} check"

- name: Restart HAProxy
  hosts: jakarta_load_balancer
  remote_user: ansible
  become: true
  tasks:
  - systemd:
      name: haproxy
      state: restarted